ALL: np_simple.cpp
	g++ np_multi_proc.cpp -o np_multi_proc
	g++ np_single_proc.cpp -o np_single_proc
	g++ np_simple.cpp -o np_simple
clean:
	rm -f np_multi_proc
	rm -f np_single_proc
	rm -f np_simple
